### ISSUE TITLE
Keep main nav menu in center even when removing "Buy Now" button

### ISSUE THREAD

**Issue by clayton-bridge** [app-generator/flask-soft-ui-design-pro#2]
In navigation.html, I would like to remove the "Buy Now" gradient button on the right hand side while still keeping the "Help" (or other main navigation items when a user is logged in) in the center of the nav bar. Right now it appears to be centering in the open space, rather than the true center of the nav bar. Can you please point out what needs to be changed and where to make this happen? Thanks!
<img width="1340" alt="Screen Shot 2022-02-03 at 12 07 42 AM" src="https://user-images.githubusercontent.com/98725836/152290293-8ec472d4-2aa9-4463-8fd6-a73d27b6ccbe.png">

**Comment by app-generator** [comment]
Hello @clayton-bridge, 

All navigation bars are saved in the `app/templates/includes` directory: 

- navigation-dark.html
- navigation-transparent.html

The `HELP` button can be found in the `main/app/templates/includes/navigation.html` file

Line: 978

**Comment by clayton-bridge** [comment]
Thanks! I was able to identify the code fine, but I could really use some help with the bootstrap class that needs to be updated. I tried all sorts of things and haven't been able to get it!

**Comment by app-generator** [comment]
Hello @clayton-bridge,

The CSS is visible in the browser inspector: 

![image](https://user-images.githubusercontent.com/51070104/152300891-0f25c04f-3c1b-4a80-9fee-b9b4f49bcec4.png)

**Comment by clayton-bridge** [comment]
Okay, thanks for reminding me about being able to change CSS in the browser inspector. That helped speed up my trial and error greatly, and I was finally able to get some CSS that works! I updated line 1209 in app/templates/includes/navigation.html to get it working. Here's my diff:

app/templates/includes/navigation.html
```
1209   -              <ul class="navbar-nav d-lg-block d-none">
1209   +              <ul class="navbar-nav d-lg-block d-none ms-sm-5 me-sm-3">
```
