### ISSUE TITLE
Nav bar location is wrong on 403 and 404 pages

### ISSUE THREAD

**Issue by clayton-bridge** [app-generator/flask-soft-ui-design-pro#3]
The nav bar sits too low on the 403 and 404 pages. See https://flask-soft-ui-design-pro.appseed-srv1.com/page-404.html and https://flask-soft-ui-design-pro.appseed-srv1.com/page-403.html for reference.
<img width="1425" alt="Screen Shot 2022-02-03 at 11 08 22 AM" src="https://user-images.githubusercontent.com/98725836/152394177-9b44cf4e-1d92-4a05-8e3e-baeeb994e33b.png">

**Comment by app-generator** [comment]
Hello @clayton-bridge, 

Noted your case. QA will take a look soon.

**Comment by app-generator** [comment]
Hello @clayton-bridge, 

Error pages now use `{% include 'includes/navigation.html' %}` component.

Please update the code for all error pages (404, 403 and 500) to use `navigation-light` component:

```html
{% block content %}
  {% include 'includes/navigation-light.html' %}
  <section class="my-10">
    <div class="container">
```

### Desktop Layout
![support-flask-soft-pro-404-layout](https://user-images.githubusercontent.com/51070104/152481031-ffc415a4-dc8f-4b97-a2bb-58ff3914725b.jpg)

### Mobile Layout
![support-flask-soft-pro-404-mobile](https://user-images.githubusercontent.com/51070104/152481057-e1d9a548-83db-4cfa-a4d8-99361fb32b5c.jpg)
